version: "2"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    container_name: elasticsearch-hands-on-2
    environment:
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - "discovery.type=single-node"
     - xpack.monitoring.collection.enabled=true
     - cluster.routing.allocation.disk.threshold_enabled=false
     - xpack.security.enabled=false
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.5
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch-hands-on-2:9200"
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

