version: "2"

services:
  elasticsearch:
    image: opensearchproject/opensearch:1.1.0
    container_name: elasticsearch-hands-on-2
    environment:
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - "discovery.type=single-node"
     - "cluster.routing.allocation.disk.threshold_enabled=false"
    ports:
      - "9200:9200"

  kibana:
    image: opensearchproject/opensearch-dashboards:1.1.0
    environment:
      OPENSEARCH_HOSTS: '["https://elasticsearch-hands-on-2:9200"]' # must be a string with no spaces when specified as an environment variable
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

