#! /bin/bash -e
#
# Run a multi-node cluster

cd "$(dirname $0)"/..

trap "docker-compose down --volumes --remove-orphans" 0

#docker-compose -f docker-compose.multi-node.yml up -d
docker-compose -f docker-compose.multi-node.yml up
